######################################################################
#
# File name : SMVM_convert_tb_simulate.do
# Created on: Mon Oct 26 19:20:35 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xbip_utils_v3_0_10 -L xbip_pipe_v3_0_6 -L xbip_bram18k_v3_0_6 -L mult_gen_v12_0_16 -L xil_defaultlib -L blk_mem_gen_v8_4_4 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.SMVM_convert_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {SMVM_convert_tb_wave.do}

view wave
view structure
view signals

log -r /*

do {SMVM_convert_tb.udo}

run 1000ns
