######################################################################
#
# File name : SMVM_convert_tb_compile.do
# Created on: Mon Oct 26 19:20:33 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/work
C:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_2019.2\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_2019.2\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_2019.2\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../project_1.srcs/sources_1/ip/mult_gen_0/sim/mult_gen_0.vhd" \

C:\\modeltech64_2019.2\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/2d50/hdl" "+incdir+../../../../project_1.srcs/sources_1/bd/design_1/ipshared/8713/hdl" "+incdir+C:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
"../../../../project_1.srcs/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \
"../../../../src/SMVM.v" \
"../../../../src/SMVM_convert.v" \
"../../../../src/SMVM_convert_tb.v" \

# compile glbl module
C:\\modeltech64_2019.2\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

