######################################################################
#
# File name : SMVM_convert_tb_wave.do
# Created on: Sun Oct 25 21:21:49 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
