######################################################################
#
# File name : top_design_wave.do
# Created on: Sun Oct 25 21:20:49 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
